#!/bin/sh

alias :e="${EDITOR}"
alias :q="exit"
alias ta="tmux attach"
alias td="tmux detach"
alias la="ls -a"
alias x="exa --classify --git --long"

j() {
    cd "$1" && ls
}
rs() {
    (redshift -x && ([ "$1" = "x" ] && return || redshift -O "$1" -g 0.9)) &>/dev/null
}
o() {
    xdg-open "$1" &>/dev/null & disown
}
sp() {
    local scratchpad="$HOME/.local/share/scratchpad"
    local sep=$(perl -E 'say "=" x 32')
    local startup_text="${sep} $(date +'%Y-%m-%d %H:%M:%S') ${sep}"
    local startup_cmd="execute \"normal Go${startup_text}\<esc>o\""

    ${EDITOR:-vim} -c ${startup_cmd} ${scratchpad}
}
gdc() {
    # git diff vs current branch
    local branch=$(git branch --show-current)
    git diff origin/$branch "$1"
}
ccat() {
    # syntax highlighting
    $(which python3) -m rich.syntax "$@"
}
