add_newline = true

[character]
success_symbol = "[❯](cyan)"
error_symbol = "[❯](red)"

[username]
disabled = true

[hostname]
disabled = true

[directory]
style = "cyan"
truncate_to_repo = false
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:247"
symbol = ""

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = "red"
conflicted = "c "
ahead = "${count}↑ "
behind = "${count}↓ "
diverged = "${ahead_count}:${behind_count}↕ "
untracked = "? "
stashed = "${count}↴ "
modified = "${count}* "
staged = "${count}+ "
renamed = "r "
deleted = "x "

[python]
disabled = true
symbol = "py "
version_format = "${major}.${minor}"
style = "green"

[cmd_duration]
disabled = true
