name: base
channels:
  - conda-forge
dependencies:
  - conda
  - python==3.13.*
  - ipython
  - ipykernel
  - pip
  - pip:
    - autoflake
    - autopep8
    - black[jupyter]
    - flake8
    - isort
    - ruff
    - jupyter-client
    - jupyter-packaging
    - jupyter-server
    - jupyter-server-mathjax
    - jupyterlab-code-formatter
    - jupyterlab-widgets
    - jupyterlab==4.*
    - loguru
    - matplotlib
    - seaborn
    - plotnine
    - plotly
    - mypy
    - nbclassic
    - nbclient
    - nbconvert
    - nbdime
    - notebook
    - numba
    - numpy
    - pandas[all]
    - ptpython
    - pynvim
    - pytest
    - rich
    - scikit-learn
    - scipy
    - typing-extensions
    - toolz
    # - altair
    # - hiplot
    # - httpx
    # - hypothesis
    # - ipympl
    # - memory-profiler
    # - mlflow
    # - more-itertools
    # - networkx
    # - nltk
    # - omegaconf
    # - Pillow
    # - plotly
    # - poetry
    # - polars
    # - pydantic
    # - pylint
    # - simple-parsing
    # - spacy
    # - statsmodels
    # - torch
    # - torchaudio
    # - torchvision
    # - transformers
    # - umap-learn
    # - wat-inspector
    # - xgboost
    # - z3-solver
