name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python==3.11.*
  - pip
  - pip:
    - ipykernel
    - ipympl
    - ipython
    - jupyter-client
    - jupyter-packaging
    - jupyter-server
    - jupyter-server-mathjax
    - jupyterlab-code-formatter
    - jupyterlab-widgets
    - jupyterlab==3.6.3 # 4 is not fully compatible with current setup
    - nbclassic
    - nbclient
    - nbconvert
    - nbdime
    - notebook
    - ptpython
    - Pillow
    - altair
    - hiplot
    - matplotlib
    - mlflow
    - networkx
    - nltk
    - numba
    - numpy
    - omegaconf
    - pandas[all]
    - plotly
    - polars
    - scikit-learn
    - scipy
    - seaborn
    - spacy
    - statsmodels
    - umap-learn
    - xgboost
    - z3-solver
    - torch
    - torchvision
    - torchaudio
    - autoflake
    - autopep8
    - black[jupyter]
    - flake8
    - httpx
    - isort
    - loguru
    - more-itertools
    - mypy
    - poetry
    - pylint
    - rich
    - ruff
    - toolz
    - typing-extensions
    - hypothesis
    - pytest
    - memory-profiler
    - pynvim
