#!/bin/bash

info=$(
	upower -i /org/freedesktop/UPower/devices/battery_BAT0 |
	awk '{ sub(/^[ \t]+/, ""); print }' |
	grep -E "state|percentage" | awk '{ print $2 }'
)

status=$(echo "$info" | sed -n '1p')
percentage=$(echo "$info" | sed -n '2p')
out=""

case "$status" in
	"charging")
		out="▲ ""$percentage" ;;
	"discharging")
		out="▼ ""$percentage" ;;
	*)
		out=""
esac

echo "$out"
