#!/bin/bash

is_mute () {
    amixer -D pulse sget Master | grep -qi "\[off\]"
}

print_volume () {
    amixer -D pulse sget Master | grep 'Right:' | awk -F'[][]' '{ print $2 }'
}

if is_mute; then echo "mute"; else print_volume; fi
