## Font
font_family      Fira Code Retina
bold_font        Fira Code Bold
italic_font      Fira Code Italic
bold_italic_font Fira Code Bold Italic

disable_ligatures always

font_size 12
adjust_baseline     5
adjust_line_height  -1
adjust_column_width -1

cursor_shape          block
cursor_blink_interval 0

remember_window_size  no
initial_window_width  1200
initial_window_height 640

window_border_width 1
window_margin_width 4

hide_window_decorations no

# os-specific
macos_option_as_alt                yes
macos_quit_when_last_window_closed yes

tab_bar_edge  top
tab_bar_style separator

## Colorscheme
cursor               #d0d0d0
background           #202020
foreground           #d8d8d8
selection_background #303030
selection_foreground #202020

# black
color0  #151515
color8  #505050

# red
color1  #ff5f5f
color9  #ff5f5f

# green
color2  #7e8d50
color10 #7e8d50

# yellow
color3  #e5b566
color11 #e5b566

# blue
color4  #6c99ba
color12 #6c99ba

# magenta
color5  #9e4e85
color13 #9e4e85

# cyan
color6  #7dd5cf
color14 #7dd5cf

# white
color7  #d0d0d0
color15 #f5f5f5
