add_newline = true

[character]
success_symbol = "[❯](cyan)"
error_symbol   = "[❯](red)"

[username]
disabled = true

[hostname]
disabled = true

[directory]
style             = "cyan"
truncate_to_repo  = true
truncation_length = 3
truncation_symbol = "…/"
read_only         = " (ro) "

[git_branch]
format = "[$symbol$branch]($style) "
style = "fg:247"
symbol = ""

[git_status]
format     = '([$all_status$ahead_behind]($style))'
style      = "red"
conflicted = "c "
ahead      = "${count}↑ "
behind     = "${count}↓ "
diverged   = "${ahead_count}:${behind_count}↕ "
untracked  = "${count}u "
stashed    = "${count}↴ "
modified   = "${count}m "
staged     = "${count}+ "
renamed    = "${count}r "
deleted    = "${count}d "

[cmd_duration]
disabled = true

# languages
[nodejs]
symbol = "node "

[python]
symbol = "py "

[rust]
symbol = "rs "

[package]
symbol = ""
