add_newline = true

[character]
success_symbol = "[❯](cyan)"
error_symbol   = "[❯](red)"

[username]
disabled = true

[hostname]
disabled = true

[cmd_duration]
disabled = true

[directory]
style             = "cyan"
truncate_to_repo  = true
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[$symbol$branch]($style)"
style = "247"
symbol = ""

[git_status]
format     = '([$all_status$ahead_behind]($style)) '
style      = "bold red"
conflicted = "c"
diverged   = "${ahead_count}:${behind_count}↕ "
ahead      = "↑"
behind     = "↓"
untracked  = "?"
stashed    = "↴"
modified   = "!"
staged     = "+"
renamed    = "r"
deleted    = "d"

[python]
format = '[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'
symbol = "py"
version_format = '${major}.${minor}'
style = "green"

[rust]
format = '[$symbol($version )]($style)'
symbol = "rs"
version_format = '${major}.${minor}'
style = "green"

[package]
disabled = true
